# Generated by Django 4.0.1 on 2022-01-11 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_post_user_userinfo_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_app.userinfo'),
        ),
    ]
