# Generated by Django 4.0.1 on 2022-01-11 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_userinfo_post_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(error_messages={'required': 'Please enter your email', 'unique': 'This email exist'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id_code',
            field=models.IntegerField(error_messages={'unique': 'This id exist'}, unique=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.IntegerField(error_messages={'required': 'Please enter your phone', 'unique': 'This phone number exist'}, help_text='Your phone number', max_length=12, unique=True),
        ),
    ]
