# Generated by Django 4.0.1 on 2022-02-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_userinfo_id_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id_code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(error_messages={'required': 'Please enter your phone', 'unique': 'This phone number exist'}, help_text='Your phone number', max_length=12, unique=True),
        ),
    ]
