# Generated by Django 4.0.1 on 2022-02-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_post_image_alter_userinfo_id_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='User',
        ),
    ]
